application: kickstarter-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
- url: /
  script: hello.app

- url: /projects
  script: projects.ProjectsHandler.app

- url: /login
  script: users.UserHandler.app

- url: /test
  static_dir: index

- url: /transaction
  script: transactions.TransactionHandler.app

- url: /styles
  static_dir: frontend/styles

- url: /bower_components
  static_dir: frontend/bower_components

- url: /views
  static_dir: frontend/views

- url: /routing
  static_dir: frontend/routing

libraries:
- name: MySQLdb
  version: "latest"
- name: webapp2
  version: latest