application: kickstarter-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
- url: /
  script: backend.main.app
  secure: always
  login: required

- url: /projects
  script: backend.projects.ProjectsHandler.app

- url: /logout
  script: backend.users.LogoutHandler.app
  secure: always

- url: /user
  script: backend.users.UserHandler.app
  secure: always

- url: /files
  script: backend.files.FilesHandler.app

- url: /transaction
  script: backend.transactions.TransactionHandler.app

- url: /styles
  static_dir: frontend/styles
  secure: always

- url: /bower_components
  static_dir: frontend/bower_components
  secure: always

- url: /views
  static_dir: frontend/views
  secure: always

- url: /images
  static_dir: frontend/images

- url: /routing
  static_dir: frontend/routing
  secure: always

- url: /projects
  script: backend.projects.ProjectsHandler.app
  secure: always

- url: /admin
  script: backend.admin.AdminHandler.app


libraries:
- name: webapp2
  version: latest