application: kickstarter-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:

- url: /api/projects
  script: backend.projects.ProjectsHandler.app

- url: /logout
  script: backend.users.LogoutHandler.app
  secure: always

- url: /api/user
  script: backend.users.UserHandler.app
  secure: always

- url: /api/files_upload
  script: backend.files.FilesHandler.app

- url: /api/file_download
  script: backend.files.FilesHandler.app

- url: /api/files
  script: backend.files.FilesHandler.app

- url: /api/transaction
  script: backend.transactions.TransactionHandler.app

- url: /api/projects
  script: backend.projects.ProjectsHandler.app
  secure: always

- url: /api/projects/.*
  script: backend.projects.ProjectsHandler.app
  secure: always

- url: /api/admin
  script: backend.admin.AdminHandler.app


libraries:
- name: webapp2
  version: latest