application: kickstarter-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
- url: /
  script: hello.app
  secure: always
  login: required

- url: /projects
  script: projects.ProjectsHandler.app
  secure: always


- url: /logout
  script: users.LogoutHandler.app
  secure: always

- url: /user
  script: users.UserHandler.app
  secure: always

- url: /transaction
  script: transactions.TransactionHandler.app
  secure: always

- url: /styles
  static_dir: frontend/styles
  secure: always

- url: /bower_components
  static_dir: frontend/bower_components
  secure: always

- url: /views
  static_dir: frontend/views
  secure: always

- url: /routing
  static_dir: frontend/routing
  secure: always


libraries:
- name: MySQLdb
  version: "latest"
- name: webapp2
  version: latest